import time
print("haiiiii gays :3")
print("i hope yall are doing weww :3")
time.sleep(0.1)
print("Anyway idk what else to write here...")
time.sleep(1.0)
print("Lorem ipsum odor amet, consectetuer adipiscing elit.")
time.sleep(0.1)
print("Sollicitudin hac auctor a lacinia platea; habitant posuere.")
time.sleep(0.1)
print("Sit nostra pellentesque feugiat habitant eros.")
time.sleep(0.1)
print("Vehicula quam egestas nisi ex facilisi curae?")
time.sleep(1.0)
print("alright, baiiii :3")
